apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agp
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../secret.yaml
  - ../../secret-postgres.yaml
  - ../../secret-minio.yaml
  - ../../networkpolicy.yaml
  - ../../pvc-data.yaml
  - ../../pvc-postgres.yaml
  - ../../pvc-minio.yaml
  - ../../pvc-artifacts.yaml
  - ../../pvc-logs.yaml
  - ../../postgres.yaml
  - ../../minio.yaml
  - ../../redis.yaml
  - ../../control-plane.yaml
  - ../../bootstrap-job.yaml
  - ../../runtime.yaml
  - ../../lease-sweeper.yaml
  - ../../runtime-sweeper.yaml
  - ../../configmap-monitoring.yaml
  - ../../prometheus.yaml
  - ../../grafana.yaml
  - ../../pvc-backups.yaml
  - ../../cronjob-backup.yaml
patches:
  - path: patch-control-plane.yaml
  - path: patch-runtime.yaml
  - path: patch-lease-sweeper.yaml
  - path: patch-runtime-sweeper.yaml
  - path: patch-bootstrap-job.yaml
  - path: patch-postgres.yaml
  - path: patch-minio.yaml
  - path: patch-backup.yaml
