apiVersion: apps/v1
kind: Deployment
metadata:
  name: lease-sweeper
spec:
  template:
    spec:
      containers:
        - name: lease-sweeper
          imagePullPolicy: IfNotPresent
      volumes:
        - $patch: replace
        - name: data
          emptyDir: {}
        - name: artifacts
          emptyDir: {}
        - name: logs
          emptyDir: {}
