apiVersion: batch/v1
kind: CronJob
metadata:
  name: agp-backup
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - $patch: replace
            - name: pgdump
              emptyDir: {}
            - name: backups
              emptyDir: {}
