apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  template:
    spec:
      containers:
        - name: control-plane
          imagePullPolicy: IfNotPresent
      volumes:
        - $patch: replace
        - name: data
          emptyDir: {}
        - name: artifacts
          emptyDir: {}
        - name: logs
          emptyDir: {}
