#!/usr/bin/env bash
set -euo pipefail

# ── Pass-through: run arbitrary commands instead of the work loop ────
if [[ $# -gt 0 && "${1}" != -* ]]; then
  exec "$@"
fi

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  exec python -m agp runtime-work-loop dummy "$@"
fi

# ── Required vars ────────────────────────────────────────────────────
: "${AGP_RUNTIME_ID:?AGP_RUNTIME_ID must be set}"
: "${AGP_SERVER_URL:?AGP_SERVER_URL must be set}"

# ── Runtime user setup ───────────────────────────────────────────────
AGP_USER="${AGP_RUNTIME_USER:-pb}"
AGP_USER_HOME="/home/${AGP_USER}"
if ! id "${AGP_USER}" &>/dev/null; then
  useradd -m -s /bin/bash "${AGP_USER}"
fi

# ── Credentials volume ─────────────────────────────────────────────
# Shared volume mounted at /credentials (read-write).  Contains per-tool
# subdirectories (claude/, codex/, …) symlinked into $HOME.  Multiple
# containers share the volume concurrently — Claude Code detects token
# refreshes via mtime and re-reads automatically.
CRED_ROOT="${AGP_CREDENTIALS_ROOT:-/credentials}"

# ── Shared env file ───────────────────────────────────────────────
# Source /credentials/.env for API keys, provider URLs, etc.
# Also install a profile.d snippet so `docker exec` shells and
# tmux/wezterm panes spawned later pick up the same vars.
if [[ -f "${CRED_ROOT}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${CRED_ROOT}/.env"
  set +a
fi
mkdir -p /etc/profile.d
cat > /etc/profile.d/agp-credentials.sh <<PROF
# Auto-generated by agp-runtime-entrypoint — do not edit.
if [ -f "${CRED_ROOT}/.env" ]; then
  set -a
  . "${CRED_ROOT}/.env"
  set +a
fi
PROF

if [[ ! -f "${CRED_ROOT}/.volume-initialized" ]]; then
  echo "FATAL: ${CRED_ROOT} is not backed by an initialized volume." >&2
  echo "Run:  skyops runtime auth   (creates volume and completes OAuth)" >&2
  echo "Then: docker run -v agp-credentials:${CRED_ROOT} ..." >&2
  exit 1
fi

# ── Symlink credential directories into $HOME ─────────────────────
# Each tool stores its data under /credentials/<name>/ and gets a
# symlink at $HOME/.<name> so tools find their config in the usual place.
for tool_dir in "${CRED_ROOT}"/*/; do
  tool_name="$(basename "${tool_dir}")"
  target="${AGP_USER_HOME}/.${tool_name}"
  # Don't clobber a real directory (e.g. if someone bind-mounts directly)
  if [[ -d "${target}" && ! -L "${target}" ]]; then
    continue
  fi
  ln -sfn "${tool_dir}" "${target}"
done

# Claude-specific: .claude.json (onboarding state) lives at $HOME.
# We store a copy inside the volume and symlink it out.
CLAUDE_DIR="${CRED_ROOT}/claude"
if [[ -f "${CLAUDE_DIR}/.claude.json" ]]; then
  ln -sf "${CLAUDE_DIR}/.claude.json" "${AGP_USER_HOME}/.claude.json"
fi

# Credential pre-flight — fail fast instead of wasting a job claim.
if [[ ! -f "${CLAUDE_DIR}/.credentials.json" ]]; then
  echo "FATAL: no credentials found at ${CLAUDE_DIR}/.credentials.json" >&2
  echo "Run:  skyops runtime auth" >&2
  exit 1
fi

# Fix ownership on critical files only (not recursive — volume may be large).
for f in "${CLAUDE_DIR}/.credentials.json" "${CLAUDE_DIR}/.claude.json" \
         "${CLAUDE_DIR}/settings.json"; do
  chown "${AGP_USER}:${AGP_USER}" "${f}" 2>/dev/null || true
done
chown "${AGP_USER}:${AGP_USER}" "${CRED_ROOT}" 2>/dev/null || true
chown -h "${AGP_USER}:${AGP_USER}" "${AGP_USER_HOME}/.claude.json" 2>/dev/null || true

# ── Git safe directories ────────────────────────────────────────────
if command -v git >/dev/null 2>&1; then
  for path in "${AGP_TMUX_DEFAULT_CWD:-}" "${AGP_WEZTERM_DEFAULT_CWD:-}" "/workspace/main"; do
    if [[ -n "${path}" && -d "${path}" ]]; then
      git config --global --add safe.directory "${path}" >/dev/null 2>&1 || true
    fi
  done
fi

# ── App permissions ──────────────────────────────────────────────────
chmod -R a+rX /app 2>/dev/null || true

# ── Build work-loop args ─────────────────────────────────────────────
HOST_KIND="${AGP_RUNTIME_TERMINAL_HOST_KIND:-tmux}"
ADAPTER_KIND="${AGP_RUNTIME_AGENT_ADAPTER_KIND:-codex}"
HOSTNAME_ARG="${AGP_RUNTIME_HOSTNAME:-$(hostname)}"
ARTIFACT_ROOT="${AGP_RUNTIME_ARTIFACT_ROOT:-/artifacts}"
IDLE_SLEEP_SECONDS="${AGP_RUNTIME_IDLE_SLEEP_SECONDS:-1}"
MAX_LOCAL_RECOVERIES="${AGP_RUNTIME_MAX_LOCAL_RECOVERIES:-1}"

ARGS=(
  python -m agp runtime-work-loop "${AGP_RUNTIME_ID}"
  --server-url "${AGP_SERVER_URL}"
  --hostname "${HOSTNAME_ARG}"
  --host-kind "${HOST_KIND}"
  --adapter-kind "${ADAPTER_KIND}"
  --artifact-root "${ARTIFACT_ROOT}"
  --idle-sleep-seconds "${IDLE_SLEEP_SECONDS}"
  --max-local-recoveries "${MAX_LOCAL_RECOVERIES}"
)

if [[ -n "${AGP_RUNTIME_AGENT_ID:-}" ]]; then
  ARGS+=(--agent-id "${AGP_RUNTIME_AGENT_ID}")
fi

if [[ -n "${AGP_RUNTIME_CAPABILITY_ID:-}" ]]; then
  ARGS+=(--capability-id "${AGP_RUNTIME_CAPABILITY_ID}")
fi

# ── Build env for the runtime user ───────────────────────────────────
USER_ENV=(
  HOME="${AGP_USER_HOME}"
  PATH="/usr/local/bin:/usr/bin:/bin"
  WEZTERM_CONFIG_FILE="${WEZTERM_CONFIG_FILE:-/etc/wezterm/wezterm.lua}"
  DISABLE_AUTOUPDATER="${DISABLE_AUTOUPDATER:-1}"
  DISABLE_TELEMETRY="${DISABLE_TELEMETRY:-1}"
  NO_UPDATE_NOTIFIER="${NO_UPDATE_NOTIFIER:-1}"
)

# Passthrough provider vars (only if set — allows explicit empty string)
for _var in \
  ANTHROPIC_API_KEY ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN \
  ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL \
  ANTHROPIC_DEFAULT_HAIKU_MODEL CLAUDE_CODE_SUBAGENT_MODEL \
  CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS \
  OPENAI_API_KEY OPENAI_BASE_URL OPENROUTER_API_KEY \
  AGP_SERVER_URL; do
  if [[ -v "$_var" ]]; then
    USER_ENV+=("${_var}=${!_var}")
  fi
done

# ── Run as non-root user ─────────────────────────────────────────────
exec runuser -u "${AGP_USER}" -- env "${USER_ENV[@]}" "${ARGS[@]}"
