"""``skyops init`` — interactive first-time setup."""

from __future__ import annotations

import platform
import shutil
import sys
from pathlib import Path

import typer

from skyops.config import SkyopsConfig

if sys.version_info >= (3, 11):
    import tomllib
else:
    try:
        import tomllib
    except ModuleNotFoundError:
        import tomli as tomllib  # type: ignore[no-redef]

init_app = typer.Typer(help="First-time setup: generate skyops.toml and connection profile.")

_SKYOPS_TOML_TEMPLATE = """\
# SkyOps configuration — generated by `skyops init`
# Override any value in skyops.local.toml (gitignored, never committed).

[stack]
mode = "{mode}"
compose_file = "compose.yaml"
project_name = "agp"

[server]
host = "0.0.0.0"
port = 7860

[database]
url = "postgresql+psycopg://agp:agp@localhost:5432/agp"

[redis]
url = "redis://localhost:6379/0"

[s3]
endpoint_url = "http://localhost:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
bucket = "agp-artifacts"

[security]
operator_token = ""
runtime_token = ""

[agents.agt_local]
capability_id = "cap_python"
workspace_profile = "main"

[workspace_profiles.main]
mode = "shared_fs"
workspace_ref = "/workspace/main"
mounts = ["@repo:/workspace/main"]

[host_profiles.default]
git_root = "/var/lib/agp/git"
worktree_root = "/var/lib/agp/worktrees"

[host_profiles.default.mount_sources]
repo = "/absolute/path/to/checkout"

[capabilities.cap_python]
name = "python"
image_ref = "local/agp:dev"
model_ref = "local"

[runtime]
host_kind = "tmux"
adapter_kind = "codex"

[monitoring]
prometheus = true
grafana = true
"""

_AGP_PROFILE_TEMPLATE = """\
# AGP connection profile — generated by `skyops init`
server_url = "http://{host}:{port}"
"""


def _existing_profile_token(profile_path: Path) -> str | None:
    if not profile_path.exists():
        return None
    try:
        with open(profile_path, "rb") as f:
            data = tomllib.load(f)
    except Exception:
        return None
    token = data.get("token")
    return token if isinstance(token, str) and token else None


def _detect_mode() -> str:
    """Suggest docker if docker is available, otherwise bare-metal."""
    return "docker" if shutil.which("docker") else "bare-metal"


def _detect_os_info() -> str:
    return f"{platform.system()} {platform.machine()}"


def _check_deps_summary() -> None:
    """Quick dependency check during init."""
    essentials = ["docker", "psql", "redis-cli"]
    for dep in essentials:
        path = shutil.which(dep)
        status = "found" if path else "MISSING"
        typer.echo(f"  {dep}: {status}")


@init_app.callback(invoke_without_command=True)
def init(
    ctx: typer.Context,
    directory: Path = typer.Option(
        Path("."), "--dir", "-d", help="Directory to write skyops.toml into."
    ),
    mode: str | None = typer.Option(
        None, "--mode", "-m", help="Stack mode: docker or bare-metal (auto-detected if omitted)."
    ),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing skyops.toml."),
) -> None:
    """Generate skyops.toml with sensible defaults."""
    if ctx.invoked_subcommand is not None:
        return

    directory = directory.resolve()
    config_path = directory / "skyops.toml"
    local_path = directory / "skyops.local.toml"

    if config_path.exists() and not force:
        typer.echo(f"skyops.toml already exists at {config_path}")
        typer.echo("Use --force to overwrite.")
        raise typer.Exit(1)

    resolved_mode = mode or _detect_mode()
    typer.echo(f"Detected: {_detect_os_info()}")
    typer.echo(f"Stack mode: {resolved_mode}")

    # Check dependencies
    typer.echo("\nChecking dependencies...")
    _check_deps_summary()

    # Write skyops.toml
    config_path.write_text(_SKYOPS_TOML_TEMPLATE.format(mode=resolved_mode))
    typer.echo(f"\nCreated {config_path}")

    # Write skyops.local.toml stub if missing
    if not local_path.exists():
        local_path.write_text(
            "# Local overrides (gitignored) — put secrets and env-specific values here.\n"
        )
        typer.echo(f"Created {local_path}")

    # Generate connection profile
    profiles_dir = Path.home() / ".agp" / "profiles"
    profiles_dir.mkdir(parents=True, exist_ok=True)
    profile_path = profiles_dir / "default.toml"
    if not profile_path.exists() or force:
        from skyops._client import _connectable_host
        cfg = SkyopsConfig()  # defaults
        existing_token = _existing_profile_token(profile_path)
        token_line = f'token = "{existing_token}"\n' if existing_token else ""
        profile_path.write_text(_AGP_PROFILE_TEMPLATE.format(
            host=_connectable_host(cfg.server.host), port=cfg.server.port,
        ) + token_line)
        typer.echo(f"Created {profile_path}")

    typer.echo("\nDone. Next steps:")
    typer.echo("  skyops config show   — review your configuration")
    typer.echo("  skyops status        — check service health")
    typer.echo("  skyops up            — start the stack")
