apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agp
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc-data.yaml
  - pvc-artifacts.yaml
  - pvc-logs.yaml
  - redis.yaml
  - control-plane.yaml
  - bootstrap-job.yaml
  - runtime.yaml
  - lease-sweeper.yaml
  - runtime-sweeper.yaml
